name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository_owner }}/kubefoods-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Configure kubectl (from KUBECONFIG secret)
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy manifests
        run: |
          sed -i "s|ghcr.io/YOUR_GITHUB_USERNAME/kubefoods-backend:latest|ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml || true
          kubectl apply -f ./k8s/deployment.yaml
          kubectl apply -f ./k8s/service.yaml || true

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/kubefoods-backend --timeout=120s

      - name: Validate deployment (health check + rollback on failure)
        run: |
          set -e
          for i in $(seq 1 12); do
            echo "Attempt $i: checking health..."
            if kubectl run --rm -i --restart=Never --image=curlimages/curl curlpod --command -- /bin/sh -c "curl -sSf http://kubefoods-service:80/healthz && echo OK"; then
              echo "Health check passed"
              exit 0
            fi
            sleep 5
          done
          echo "Health check failed — rolling back"
          kubectl rollout undo deployment/kubefoods-backend
          exit 1