apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefoods-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubefoods
  template:
    metadata:
      labels:
        app: kubefoods
    spec:
      containers:
        - name: backend
          image: ghcr.io/YOUR_GITHUB_USERNAME/kubefoods-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 20